name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker build -t test-image -f Dockerfile.test .
        docker run test-image

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push production image
      run: |
        docker build -t my-production-image:latest .
        docker push my-production-image:latest

    - name: Deploy to production
      run: ./deploy_script.sh
