name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build test image
      run: docker build -t test-image -f Dockerfile.test .

    - name: Run tests
      run: docker run test-image pytest api/tests

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Write GCP SA Key to File
      run: echo '${{ secrets.GCP_SA_KEY }}' > ./gcp-sa-key.json

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Apply Terraform changes
      env: 
        TF_VAR_project_id: "media-djinn"
        TF_VAR_gcp_credentials_file: "../gcp-sa-key.json"
        TF_VAR_region: "us-west1"
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Authenticate Docker to Google Artifact Registry
      run: gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Build and push production image to Artifact Registry
      run: |
        docker build -t us-west1-docker.pkg.dev/media-djinn/media-djinn-registry/flix-fire-scraper-image:latest .
        docker push us-west1-docker.pkg.dev/media-djinn/media-djinn-registry/flix-fire-scraper-image:latest
